import { test, expect } from '@playwright/test'

test('opens example and navigates core STRIDE workflow', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveTitle(/Threat Atlas/)
  await expect(page.getByRole('heading', { name: 'Threat models' })).toBeVisible()
  await page.getByRole('button', { name: /Online Banking Example/ }).click()
  await expect(page.getByText('Web Application', { exact: true })).toBeVisible()
  await page.getByText('Web Application', { exact: true }).click()
  await page.getByRole('button', { name: /Threats 1/ }).click()
  await expect(page.getByText('Credential Stuffing Against Customer Login')).toBeVisible()
  await page.getByRole('button', { name: /Review/ }).click()
  await expect(page.getByRole('heading', { name: 'Threat review' })).toBeVisible()
  await expect(page.getByText('Modification of API Requests')).toBeVisible()
})

test('creates and persists a model and process', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Create model' }).click()
  await page.getByRole('button', { name: 'Process', exact: true }).click()
  await expect(page.locator('.react-flow__node').getByText('New Process')).toBeVisible()
  await page.waitForTimeout(600)
  await page.reload()
  await expect(page.locator('.react-flow__node').getByText('New Process')).toBeVisible()
})

test('contained nodes remain selectable after selecting a boundary and nodes resize', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Online Banking Example/ }).click()
  await page.getByText('Application Network', { exact: true }).click()
  await page.getByText('Web Application', { exact: true }).click()
  await expect(page.getByRole('complementary').getByText('Web Application', { exact: true })).toBeVisible()
  const node = page.locator('.react-flow__node').filter({ hasText: 'Web Application' }), before = await node.boundingBox()
  const box = await node.locator('.atlas-resize-handle').last().boundingBox()
  expect(box).not.toBeNull()
  await page.mouse.move(box!.x + 5, box!.y + 5)
  await page.mouse.down()
  await page.mouse.move(box!.x + 55, box!.y + 35, { steps: 5 })
  await page.mouse.up()
  const after = await node.boundingBox()
  expect(after!.width).toBeGreaterThan(before!.width)
})

test('adds, moves, routes, removes, and persists canvas waypoints', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Online Banking Example/ }).click()
  await page.locator('.flow-label').first().dblclick()
  const handle = page.getByRole('button', { name: 'Move waypoint 1' })
  await expect(handle).toBeVisible()
  const labelBox = await page.locator('.flow-label').first().boundingBox()
  const before = await handle.boundingBox()
  expect(labelBox!.x + labelBox!.width < before!.x || before!.x + before!.width < labelBox!.x || labelBox!.y + labelBox!.height < before!.y || before!.y + before!.height < labelBox!.y).toBeTruthy()
  await page.mouse.move(before!.x + 7, before!.y + 7)
  await page.mouse.down()
  await page.mouse.move(before!.x + 87, before!.y + 57, { steps: 6 })
  await page.mouse.up()
  const after = await handle.boundingBox()
  expect(after!.x).toBeGreaterThan(before!.x + 50)
  await page.locator('.react-flow__pane').click({ button: 'right', position: { x: 30, y: 30 } })
  await expect(page.locator('.context-menu')).toBeVisible()
  await handle.click({ button: 'right' })
  await expect(page.locator('.context-menu')).toHaveCount(0)
  await expect(page.locator('.waypoint-menu')).toHaveCount(1)
  await page.getByRole('button', { name: 'Smooth' }).click()
  await page.waitForTimeout(500)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Move waypoint 1' })).toBeVisible()
  const viewport = page.locator('.react-flow__viewport')
  const transformBeforeRemoval = await viewport.getAttribute('style')
  await page.getByRole('button', { name: 'Move waypoint 1' }).click({ button: 'right' })
  await page.getByRole('button', { name: 'Delete waypoint' }).click()
  await expect(page.getByRole('button', { name: 'Move waypoint 1' })).toHaveCount(0)
  await page.locator('.react-flow__pane').dblclick({ position: { x: 30, y: 30 } })
  await expect(viewport).toHaveAttribute('style', transformBeforeRemoval!)
})
