import { create } from 'zustand'; import type { AtlasEdge, AtlasNode, ElementType, StrideId, ThreatModel } from './domain'; import { emptyMetadata, uid } from './domain'; import { saveModel } from './storage'
type Selection={kind:'node'|'edge';id:string}|null
interface State {model:ThreatModel|null;selection:Selection;saveState:'saved'|'saving';past:ThreatModel[];future:ThreatModel[];clipboard:{nodes:AtlasNode[];edges:AtlasEdge[]}|null; setModel:(m:ThreatModel)=>void; mutate:(fn:(m:ThreatModel)=>void,history?:boolean)=>void; select:(s:Selection)=>void; addNode:(type:ElementType,p:{x:number;y:number})=>string; addEdge:(s:string,t:string)=>void; addThreat:(elementId:string,cat:StrideId)=>string; deleteSelection:()=>void; undo:()=>void;redo:()=>void; copy:()=>void;paste:()=>void;duplicate:()=>void }
let timer:number|undefined
export const useStore=create<State>((set,get)=>({model:null,selection:null,saveState:'saved',past:[],future:[],clipboard:null,
 setModel:m=>{localStorage.setItem('ta-active-model',m.id);set({model:m,selection:null,past:[],future:[],saveState:'saved'})},select:selection=>set({selection}),
 mutate:(fn,history=true)=>{const m=get().model;if(!m)return;const before=structuredClone(m),next=structuredClone(m);fn(next);next.updatedAt=new Date().toISOString();set({model:next,saveState:'saving',past:history?[...get().past.slice(-49),before]:get().past,future:history?[]:get().future});clearTimeout(timer);timer=window.setTimeout(async()=>{await saveModel(next);set({saveState:'saved'})},350)},
 addNode:(type,p)=>{const id=uid();get().mutate(m=>m.nodes.push({id,type,name:{external:'External Entity',process:'New Process',store:'Data Store',boundary:'Trust Boundary'}[type],position:p,size:type==='boundary'?{width:440,height:280}:undefined,metadata:emptyMetadata(),zIndex:type==='boundary'?-10:1}));set({selection:{kind:'node',id}});return id},
 addEdge:(source,target)=>get().mutate(m=>m.edges.push({id:uid(),source,target,label:'Data flow',description:'',protocol:'',port:'',authentication:'',encryption:'',dataClassification:'',notes:''})),
 addThreat:(elementId,strideCategory)=>{const id=uid();get().mutate(m=>{const t=new Date().toISOString();m.threats.push({id,displayId:`TA-${String(m.nextThreatNumber++).padStart(3,'0')}`,elementId,title:`New ${strideCategory.replaceAll('-',' ')} threat`,strideCategory,status:'open',description:'',impact:'',attackScenario:'',remediation:'',residualRisk:'',references:'',tags:[],likelihood:'',impactRating:'',owner:'',dueDate:'',verification:'',notes:'',createdAt:t,updatedAt:t});m.reviewState[elementId]={...(m.reviewState[elementId]||{}),[strideCategory]:'threat-identified'}});return id},
 deleteSelection:()=>{const s=get().selection,m=get().model;if(!s||!m)return;const count=m.threats.filter(t=>t.elementId===s.id).length;if(count&&!confirm(`This element has ${count} associated threat${count===1?'':'s'}.\n\nDelete element and threats?`))return;get().mutate(x=>{if(s.kind==='node'){x.nodes=x.nodes.filter(n=>n.id!==s.id);const edgeIds=new Set(x.edges.filter(e=>e.source===s.id||e.target===s.id).map(e=>e.id));x.edges=x.edges.filter(e=>!edgeIds.has(e.id));x.threats=x.threats.filter(t=>t.elementId!==s.id&&!edgeIds.has(t.elementId))}else{x.edges=x.edges.filter(e=>e.id!==s.id);x.threats=x.threats.filter(t=>t.elementId!==s.id)}});set({selection:null})},
 undo:()=>{const p=get().past,m=get().model;if(!m||!p.length)return;const prev=p.at(-1)!;set({model:prev,past:p.slice(0,-1),future:[m,...get().future],selection:null});saveModel(prev)},redo:()=>{const [next,...rest]=get().future,m=get().model;if(!m||!next)return;set({model:next,past:[...get().past,m],future:rest,selection:null});saveModel(next)},
 copy:()=>{const s=get().selection,m=get().model;if(!s||!m)return;if(s.kind==='node')set({clipboard:{nodes:m.nodes.filter(n=>n.id===s.id),edges:[]}})},paste:()=>{const c=get().clipboard;if(!c)return;let id='';get().mutate(m=>{for(const old of c.nodes){id=uid();m.nodes.push({...structuredClone(old),id,name:`${old.name} copy`,position:{x:old.position.x+30,y:old.position.y+30}})}});if(id)set({selection:{kind:'node',id}})},duplicate:()=>{get().copy();get().paste()}
}))
